Pylons/pyramid_debugtoolbar

pyramid_debugtoolbar/panels/request_vars.py, pyramid_debugtoolbar/panels/templates/request_vars.dbtmako
The keys for POST vars with duplicate names were being (correctly) listed in their orignal order, however *all* values for each of these keys were (incorrectly) listed for each occurance of the duplicated keys.
This is particularly confusing, e.g., when looking at, e.g. [peppercorn](http://peppercorn.readthedocs.org/)-encoded data. By way of example, currently peppercorn data consisting of two simple mappings is currently (incorrectly) displayed as:
Variable | Value
---------- | ----------
\__start\__	| u'A:mapping', u'B:mapping'
score	| u'1', u'2'
\__end\__	| u'A:mapping', u'B:mapping'
\__start\__	| u'A:mapping', u'B:mapping'
score	| u'1', u'2'
\__end\__	| u'A:mapping', u'B:mapping'
With this patch, the same data is correctly displayed as:
Variable | Value
---------- | ---------- …
=> Fix display of repeated POST vars

pyramid_debugtoolbar/static/js/debugger.js
Looks like typo in ``window`` variable name.
=> fix typo in debugger.js

CHANGES.txt, CONTRIBUTORS.txt, pyramid_debugtoolbar/views.py, setup.py, tests/test_auth.py
Also, adds tests for the auth system.
Closes #223.
=> Allow the auth predicate to protect toolbar views.

.travis.yml, CHANGES.txt, pyramid_debugtoolbar/__init__.py, pyramid_debugtoolbar/toolbar.py, setup.py, tests/test_toolbar.py, tox.ini
pyramid_debugtoolbar doesn't run under Pyramid 1.2.x anymore because the latest pyramid_mako requires an API introduced in 1.3
closes #224.
=> Adds Pyramid version tests; bumps required version.

CONTRIBUTORS.txt, pyramid_debugtoolbar/panels/sqla.py
It is not used anymore and results in `UnicodDecode` exceptions when there
are unicode characters in the query statement
=> Remove the query hash.

CHANGES.txt, pyramid_debugtoolbar/panels/templates/versions.dbtmako, pyramid_debugtoolbar/panels/versions.py
I found it increasingly difficult to tell which version of a package was being used (the official release in my virtualenv or a forked version via `setup.py develop`).  
Simple fix - add the package's `location` to the "Versions" panel.
=> added Location to Versions panel

CHANGES.txt, pyramid_debugtoolbar/panels/request_vars.py, pyramid_debugtoolbar/panels/templates/request_vars.dbtmako
=> showing more info on the request panel

pyramid_debugtoolbar/panels/templates/sqlalchemy_select.dbtmako
The results for a SQL query are presented in a table with one column per parameter. This can easily overflow the panel.
=> SQL result table overflows panel

pyramid_debugtoolbar/__init__.py, pyramid_debugtoolbar/panels/traceback.py, pyramid_debugtoolbar/toolbar.py, pyramid_debugtoolbar/utils.py, pyramid_debugtoolbar/views.py, tests/test_auth.py, tests/test_toolbar.py
The tween will now dispatch directly to the toolbar for content instead of invoking subrequests into the parent application.
The benefits of this approach are that we are no longer subject to any odd configuration in the parent app that may affect the toolbar's view.
The toolbar was also registering pyramid_mako and was using the parent app to actually render the redirect interceptions and all of the exception views. I moved things around such that the toolbar app is now always used for rendering instead of the parent app.
=> refactor the toolbar out of the parent app

docs/api.rst, docs/index.rst, pyramid_debugtoolbar/__init__.py, pyramid_debugtoolbar/toolbar.py, pyramid_debugtoolbar/utils.py, tests/test_init.py, tests/test_toolbar.py
This is useful for extensions that wish to define their own includeme
that is added via ``debugtoolbar.includes``. An extension can now
register its own panel.
This should become the primary way of defining toolbar panels because the panel can be added in conjunction with other configuration such as urls and static assets if necessary. For example:
```python
def includeme(config):
config.add_debugtoolbar_panel(panel)
config.add_static_view(...)
config.add_route(...)
config.add_view(...)
```
These routes and views are now accessible within the toolbar app at `http://localhost:6543/_debug_toolbar/...`.
=> add a new add_debugtoolbar_panel directive to the toolbar app

CHANGES.txt, pyramid_debugtoolbar/__init__.py, tests/test_toolbar.py
This is a fix for https://github.com/Pylons/pyramid_debugtoolbar/issues/47. Basically we wait until the app is created and all config is done before we add our final subscriber to the list... putting it last in the order. Since it is last it should no longer miss anything. The attached test fails when executed without this fix.
This depends on #283 for tests.
=> fix before render subscriber order

CHANGES.txt, demo/demo.py, demo/sqla.py, pyramid_debugtoolbar/toolbar.py
Tested using gunicorn in multiprocess mode via ``gunicorn -w 4 demo:app``. Also confirmed that the warning is not emitted when using a single process via ``gunicorn demo:app``.
Fixes #245.
=> add a warning when the wsgi server is multiprocess

pyramid_debugtoolbar/static/toolbar/toolbar.js
There was a slight change in one of the recent mako templates the broke the sticky panel functionality.  This restores it.
=> updated stickypanel to address current id

CONTRIBUTORS.txt, pyramid_debugtoolbar/templates/history_tab.dbtmako, pyramid_debugtoolbar/toolbar_app.py
* Removed route predicate on the debugtoolbar.request route to prevent 404.
* Added logic into template to show warning.
=> fix #302: show warning instead of 404 for orphaned debug sessions

pyramid_debugtoolbar/panels/traceback.py, pyramid_debugtoolbar/tbtools.py, pyramid_debugtoolbar/toolbar.py, tests/test_toolbar.py, tests/test_views.py
The original fix for #302 in PR #303 broke the exception panel as it caused exception requests to be caught by the wrong route. This fixes it by moving the token from the query string to the path.
And yes, the test now pass.
=> Fix broken exception handling introduced by PR #303

pyramid_debugtoolbar/utils.py, tests/test_utils.py
Fix for IPv6 local iface notation by splitting at '%' and using the
first part (#166). Also add some IPv6 unit test cases.
=> Fix for IPv6 local iface notation

CHANGES.txt, CONTRIBUTORS.txt, pyramid_debugtoolbar/panels/headers.py
=> Defer response headers processing to a finished callback

demo/demo.py, docs/index.rst, pyramid_debugtoolbar/__init__.py, pyramid_debugtoolbar/panels/sqla.py, pyramid_debugtoolbar/panels/templates/traceback.dbtmako, pyramid_debugtoolbar/panels/traceback.py, pyramid_debugtoolbar/static/debugger/debugger.js, pyramid_debugtoolbar/tbtools.py, pyramid_debugtoolbar/templates/exception.dbtmako, pyramid_debugtoolbar/toolbar.py, pyramid_debugtoolbar/toolbar_app.py, pyramid_debugtoolbar/utils.py, tests/test_auth.py, tests/test_toolbar.py, tests/test_views.py
So this turned into a bit of a rabbit hole cleaning up a lot of cruft in the toolbar with regard to exceptions.
1. Tracebacks are now tied to the per-request toolbar object one-to-one. A request may have one traceback. Previously they actually stuck around for the entire lifetime of the app instead of being collected by the `max_request_history` setting.
2. The routes for exceptions are standardized to look similar to the SQLA ajax routes. For example, `/{request_id}/exception` instead of `/exception?token=...&tb=...` and `/{request_id}/exception/execute/{frame_id}?cmd=...` instead of `/exception?token=...&tb=...&frm=...&cmd=...`.
3. Fixed the url generation for the traceback panel link at the bottom of the traceback... it was actually empty previously - it got lost somewhere along the …
=> Fix tracebacks

CHANGES.txt, demo/demo.py, pyramid_debugtoolbar/toolbar.py
On python < 3.5 `logger.exception` would force the `exc_info` parameter to `1` or `True` (depending on the version). In 3.5 it was switched to a default kwarg that could be overridden. This fix uses `log.error` instead which does not force the value of `exc_info` on any version of Python.
fixes #319
=> squashed exceptions would cause a bug when logging the output

src/pyramid_debugtoolbar/static/debugger/debugger.js, src/pyramid_debugtoolbar/static/toolbar/toolbar.js
it looks like the 4.2/4.3 branches rewrote some debugger.js functionality that is not universally compatible with all browsers. the trailing commas in a few places can completely break the debugger in some browsers; the lack of semicolons in some other places might cause issues as well.
this is just a light edit for full compatibility against the jshint defaults (http://jshint.com/, http://jshint.com/install/)
this doesn't comply with the stricter tool jslint (http://jslint.com/, https://github.com/douglascrockford/JSLint)
this PR integrates PR #325 to fix a similar issue in some browsers as well.
=> javascript fixes for jshint/etc

CONTRIBUTORS.txt, docs/index.rst, src/pyramid_debugtoolbar/toolbar.py
When migrating from pylons to pyramid the log output was way too noisy because of squashed exception information, this allows us to control if we want to see the information at all.
=> exceptions: allow a way to supress squashed exceptions logging

src/pyramid_debugtoolbar/toolbar.py, src/pyramid_debugtoolbar/utils.py, tests/test_toolbar.py, tests/test_utils.py
Some middleware box, not identified in issue #85 is inserting additional
IP addresses for the proxies in the REMOTE_ADDR environ variable.
That's not what it is for, it is supposed to provide the IP address of
the client that made the original request, and then X-Forwarded-For
contains additional information.
However middleware boxes being the type of quality they usually are, we
can't rely on them always placing the proxy IP address first, followed
by the client IP address last.
Especially since X-Forwarded-For is specified as <client>, <proxy 1>,
<proxy 2> and thus is the reverse of whateve this mess is.
So instead we bail out. If you own such a middleware box that sets
REMOTE_ADDR this way, please, for all that is good, please let me know
what it is and who authored it.
Your final WSGI …
=> Remove parsing of REMOTE_ADDR when it contains a comma

docs/index.rst
Hello,
As confirmed on IRC those 2 functions should actually be properties.
Kind regards,
=> [doc/fix] SampleDebugPanel.title/nav_title are properties

src/pyramid_debugtoolbar/panels/sqla.py
I use GeoAlchemy which can use JSON parameters.
Serializing these parameters can generate ValueError, which are not handled in SQLA debug panel...
=> Handle ValueError in SQLAlchemy debug panel

CONTRIBUTORS.txt, src/pyramid_debugtoolbar/toolbar.py
Issue #359
I took the liberty to change the template's string to use the `format` method as I found other usages of `format` so I think its within the Python versions you support.
Still need to test this.
=> Inject closing slash character if content_type of response is xhtml 

src/pyramid_debugtoolbar/panels/request_vars.py, src/pyramid_debugtoolbar/panels/templates/request_vars.dbtmako, tests/test_panels/_utils.py, tests/test_panels/test_request_vars.py
* extend RequestVars Panel with POST data
* extend test suite to test the Panel
This should have everything discussed in the #364, applied on top of HEAD. Github would not let me re-open the PR after I force-pushed the rebase and edits.
=> redo of #332

setup.cfg, src/pyramid_debugtoolbar/panels/sqla.py, tests/test_panels/_utils.py, tests/test_panels/test_sqla.py
Use the SQLAlchemy Events system to add transactional markers (such as `begin`, `commit`, `rollback`) to the debug payload
* redo of #299
* closes #236
Two things to note for code review:
1) Tests do not cover "two phase" transaction events, because Sqlite does not support them. The tests would have to run against a db like mysql, or a mocked system. I don't have the time to build out the mocked system, and adding a mysql service container is doable but questionable - so I am okay with removing these events.
2) The standard library's Sqlite driver has long had a problem with transaction levels.  The workarounds have been to:
* use the pysqlite driver
* use SQLAlchemy event listeners
I opted to use the latter option and minimize another testing include.  After some testing, the stdlib …
=> SQLAlchemy Panel - log transactional events

src/pyramid_debugtoolbar/panels/session.py
There is a small typo in src/pyramid_debugtoolbar/panels/session.py.
Should read `attribute` rather than `attibute`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, attibute -> attribute

src/pyramid_debugtoolbar/panels/logger.py
`threading.currentThread` was deprecated in Python 3.10 (October 2021).
Replace with `threading.current_thread`, added in Python 2.6 (October 2008).
* https://docs.python.org/3.12/whatsnew/3.10.html#deprecated
* https://github.com/python/cpython/pull/25174
=> Replace deprecated threading.currentThread with current_thread

.github/workflows/ci-tests.yml, CONTRIBUTORS.txt, demo/sqla.py, src/pyramid_debugtoolbar/panels/sqla.py, tests/test_panels/_utils.py, tests/test_panels/test_request_vars.py, tests/test_panels/test_sqla.py, tox.ini
SQLAlchemy 2.0 [removes the "connectionless" execution option](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#implicit-and-connectionless-execution-bound-metadata-removed) and requires the use of a new context manager [connection API](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-core-connection-transaction). This pull request adjusts the pyramid debugtoolbar SQLAlchemy panel to use this new style.
- I don't think this new style will work with sqlalchemy older than 1.4; how should that be handled?
- `connection.execute()` expects a different bind-param style than is generated here; `exec_driver_sql` worked for me with psycopg2, but I'm not sure if it's correct for other drivers.
=> Use SQLAlchemy 2.x execution API

CHANGES.txt, docs/conf.py, setup.cfg, src/pyramid_debugtoolbar/panels/templates/versions.dbtmako, src/pyramid_debugtoolbar/panels/versions.py
sadly importlib.metadata does not make it possible to get the location of a package since it's trying to abstract that detail now... we could detect a PathDistribution but that's a private api and doesn't seem worth it.
=> drop setuptools / pkg_resources

CHANGES.txt, src/pyramid_debugtoolbar/__init__.py, src/pyramid_debugtoolbar/panels/request_vars.py, src/pyramid_debugtoolbar/utils.py
- The toolbar has been triggering a deprecation warning due to its incorrect wrapping of request.effective_principals.
=> fix inadvertent deprecation warnings triggered by using the toolbar
